FROM ruby:2.6.5-alpine3.10

WORKDIR /usr/app/src

# COPIAR PROYECTO A /usr/app/src

# INSTALAR las gemas

# expose del puerto (ver con rails s(creo que 3000))

# mandar a correr el rails s con el proyecto